 $(function(){
 	$(".xinpin").toggle(
	 	function(){
	 		$(".xinpincaidan").css("display","block");	
	 	},
	 	function(){
	 		$(".xinpincaidan").css("display","none");
	 	});
	$(".fuzhuang").toggle(
	 	function(){
	 		$(".fuzhuangcaidan").css("display","block");	
	 	},
	 	function(){
	 		$(".fuzhuangcaidan").css("display","none");
	 	});	
 	$(".peishi").toggle(
 		function(){
 		$(".peishicaidan").css("display","block");	
 		},
 		function(){
 		$(".peishicaidan").css("display","none");
 	});
	$(".cuxiao").toggle(
	 	function(){
	 		$(".cuxiaocaidan").css("display","block");	
	 	},
	 	function(){
	 		$(".cuxiaocaidan").css("display","none");
	});
 })
 